### ISSUE TITLE
2.5.0 crashes on Windows as soon as an app launches

### ISSUE THREAD

**Issue by ishitatsuyuki** [GPUOpen-Tools/radeon_developer_panel#15]
A freshly downloaded RDP 2.5.0 is completely unusable --- it crashes as soon as an app launches, and has other malfunctioning symptoms:

- Typing anything in System -> My Application -> Advanced Mode -> Application Name... triggers a crash.
- "Blocked Application" is empty, has "TextLabel" as its title

System:
- Windows 10 21H2
	- Locale: Japanese
- AMD Radeon 5700 XT
- Driver 22.3.2

A previously downloaded RDP 2.4.0 (RadeonDeveloperToolSuite-2021-06-30-819) runs completely fine and was able to capture a trace.

Log:

[log.txt](https://github.com/GPUOpen-Tools/radeon_developer_panel/files/8372896/log.txt)

**Comment by ishitatsuyuki** [comment]
This turned out to be a duplicate of https://github.com/GPUOpen-Tools/radeon_gpu_profiler/issues/63. As such, the options are either to not use a English locale OS, or just downgrade to a previous version of Panel.

**Comment by mguerret-amd** [comment]
This should be resolved with the latest RGP 1.13 and RDP 2.6 release:
https://gpuopen.com/rgp-1-13-rdp-2-6/

**Comment by v4vendeta** [comment]
Met the same problem on Radeon Developer Panel 2.6.0.34, here is the log file

[log.txt](https://github.com/GPUOpen-Tools/radeon_developer_panel/files/8695349/log.txt)

**Comment by jshofmann** [comment]
RadeonDeveloperPanel.exe from the RadeonDeveloperToolSuite-2022-08-01-115.zip is crashing on attach as well. EN-US located Windows 11 Pro 21H2 build 22000.856 with Windows Feature Experience Pack 1000.22000.856.0. RDP.exe also crashes if you turn Advanced Mode on in the System tab and enter any keystroke at all in the Executable Name field, no external app using D3D12 required, see attached log and dump.
[crash-20220812-175516.zip](https://github.com/GPUOpen-Tools/radeon_developer_panel/files/9330302/crash-20220812-175516.zip)
 
This log and dump is from launching the D3D12ExecuteIndirect.exe sample program available at https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop/D3D12ExecuteIndirect while RadeonDeveloperPanel.exe is open.
[crash-20220812-175928.zip](https://github.com/GPUOpen-Tools/radeon_developer_panel/files/9330303/crash-20220812-175928.zip)

**Comment by MathiasMagnus** [comment]
Same here.
- RadeonDeveloperToolSuite-2022-08-01-115.zip
- Windows 11 Pro 22H2 22621.608
- HU-hu localized system
- GA402RK laptop (Ryzen 6800HS + Radeon 6800S)
- Radeon Software 22.8.2

Crashes when opening just about _any_ executable I throw at it.

**Comment by codeonwort** [comment]
Still crashing on RDP v2.7.0.25 due to locale issue.

As @ishitatsuyuki mentioned the locale matters. Launching a rendering application or using some menu in RDP causes a crash immediately if the OS locale is not English.

![os_locale](https://user-images.githubusercontent.com/11644393/195570794-a9332354-62ae-475e-8f03-a88405c43af2.jpg)

Switching my locale from Korean to English solved the issue but I don't wanna change my locale everytime to use RDP.

I'm sure this is locale-related, not about my application nor GPU driver, because PIX on Windows works no matter what my locale is, RDP crashes only if the locale is Non-English, and RDP minidump says something's wrong with Qt UI thread.

[dump.zip](https://github.com/GPUOpen-Tools/radeon_developer_panel/files/9775629/dump.zip)

**Comment by mguerret-amd** [comment]
@codeonwort This issue will be resolved in the next release of RDP

**Comment by MathiasMagnus** [comment]
@mguerret-amd Will there be a December release of Radeon Developer Panel with the fix? I'd be fine launching some service manually and invoking a command-line tool, to get some `rocprof`-like experience on Windows and dig through CSV files to my heart's desire... this issue has been in place for 9 months now.

**Comment by mguerret-amd** [comment]
This should be resolved with the latest RDP v2.8 release. Please file a new issue if the crash persists in 2.8
